//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Officecore.Website.layouts.Officecore.Controls {
    using Sitecore.Web.UI.WebControls;

    public partial class Embed_Social_Login {
        
        /// <summary>
        /// SocialLogins control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected Placeholder SocialLogins;
    }
}
