//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Officecore.Website.layouts.Officecore.EmailCampaign {
    using System.Web.UI.WebControls;

    using Sitecore.Web.UI.WebControls;

    using Image = Sitecore.Web.UI.WebControls.Image;

    public partial class EmailPromoSpot {
        
        /// <summary>
        /// promoImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected Image promoImage;
        
        /// <summary>
        /// promoLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected HyperLink promoLink;
        
        /// <summary>
        /// promoTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected Text promoTitle;
        
        /// <summary>
        /// promoDescription control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected Text promoDescription;
    }
}
